### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by deepansharya1111** [ThanhNhann/nervos#1]
Hi, can you please help me in understanding one thing in task 3? I'm stuck at the first step, where we have to replace "Read Function Name" and "Write Function Name" in the index.json file. I couldn't understand where to find these function names, can you guide me, please?

**Comment by ThanhNhann** [comment]
with `Read  Function Name` you change it to `get` and with `Write Function Name` you change to `set(10)`, good luck

**Comment by deepansharya1111** [comment]
Thanks a lot! it worked :)
